export interface KimchiType {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  region: string;
  spicyLevel: number; // 1-5
  fermentationLevel: number; // 1-5
  saltiness: number; // 1-5
  crunchiness: number; // 1-5
  mainIngredients: string[];
  bestWith: string[]; // 어울리는 음식
  healthBenefits: string[];
  imageUrl: string;
  tags: string[];
}

export const KIMCHI_DATA: KimchiType[] = [
  {
    id: "baechu",
    name: "배추김치",
    nameEn: "Napa Cabbage Kimchi",
    description: "가장 대표적인 한국 김치. 배추를 소금에 절여 고춧가루, 젓갈, 마늘 등으로 양념하여 발효시킨 김치입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 4,
    saltiness: 3,
    crunchiness: 4,
    mainIngredients: ["배추", "고춧가루", "젓갈", "마늘", "생강"],
    bestWith: ["삼겹살", "김치찌개", "김치볶음밥", "라면"],
    healthBenefits: ["유산균 풍부", "비타민 C", "식이섬유", "면역력 강화"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["전통", "발효", "매운맛", "기본"],
  },
  {
    id: "kkakdugi",
    name: "깍두기",
    nameEn: "Cubed Radish Kimchi",
    description: "무를 깍둑썰기하여 고춧가루 양념에 버무린 김치. 아삭한 식감이 특징입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 5,
    mainIngredients: ["무", "고춧가루", "젓갈", "마늘", "파"],
    bestWith: ["설렁탕", "곰탕", "순대국", "수육"],
    healthBenefits: ["소화 촉진", "비타민 C", "식이섬유"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Kkakdugi.jpg/800px-Kkakdugi.jpg",
    tags: ["아삭함", "국물요리", "담백"],
  },
  {
    id: "chonggak",
    name: "총각김치",
    nameEn: "Ponytail Radish Kimchi",
    description: "총각무를 통째로 담근 김치. 알싸한 맛과 아삭한 식감이 특징입니다.",
    region: "전국",
    spicyLevel: 4,
    fermentationLevel: 4,
    saltiness: 3,
    crunchiness: 5,
    mainIngredients: ["총각무", "고춧가루", "젓갈", "마늘"],
    bestWith: ["고기구이", "비빔밥", "보쌈"],
    healthBenefits: ["소화 촉진", "항산화 작용"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Chonggak-kimchi.jpg/800px-Chonggak-kimchi.jpg",
    tags: ["알싸함", "아삭함", "전통"],
  },
  {
    id: "nabak",
    name: "나박김치",
    nameEn: "Water Kimchi",
    description: "무와 배추를 납작하게 썰어 시원한 국물과 함께 담근 물김치입니다.",
    region: "전국",
    spicyLevel: 1,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["무", "배추", "미나리", "쪽파"],
    bestWith: ["면요리", "밥", "여름철 식사"],
    healthBenefits: ["수분 보충", "소화 촉진", "청량감"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Nabak-kimchi.jpg/800px-Nabak-kimchi.jpg",
    tags: ["시원함", "물김치", "여름"],
  },
  {
    id: "dongchimi",
    name: "동치미",
    nameEn: "Radish Water Kimchi",
    description: "무를 통째로 소금물에 담가 발효시킨 겨울철 대표 물김치입니다.",
    region: "전국",
    spicyLevel: 1,
    fermentationLevel: 4,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["무", "배", "대파", "마늘"],
    bestWith: ["냉면", "만두", "겨울철 식사"],
    healthBenefits: ["소화 촉진", "해독 작용", "수분 보충"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Dongchimi_%EB%8F%99%EC%B9%98%EB%AF%B8.jpg/800px-Dongchimi_%EB%8F%99%EC%B9%98%EB%AF%B8.jpg",
    tags: ["시원함", "물김치", "겨울", "냉면"],
  },
  {
    id: "yeolmu",
    name: "열무김치",
    nameEn: "Young Radish Kimchi",
    description: "어린 무청을 이용해 담근 여름철 별미 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["열무", "고춧가루", "멸치액젓"],
    bestWith: ["비빔밥", "비빔국수", "열무냉면"],
    healthBenefits: ["비타민 풍부", "청량감"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Yeolmu-kimchi.jpg/800px-Yeolmu-kimchi.jpg",
    tags: ["여름", "상큼함", "비빔"],
  },
  {
    id: "oisobagi",
    name: "오이소박이",
    nameEn: "Stuffed Cucumber Kimchi",
    description: "오이에 칼집을 내어 부추와 양념소를 채워 넣은 여름철 김치입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 5,
    mainIngredients: ["오이", "부추", "고춧가루", "마늘"],
    bestWith: ["보리밥", "된장찌개", "삼겹살"],
    healthBenefits: ["수분 보충", "비타민 K", "청량감"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Oi-sobagi.jpg/800px-Oi-sobagi.jpg",
    tags: ["여름", "아삭함", "시원함"],
  },
  {
    id: "gat",
    name: "갓김치",
    nameEn: "Mustard Leaf Kimchi",
    description: "갓 특유의 알싸하고 톡 쏘는 맛이 특징인 전라도 대표 김치입니다.",
    region: "전라도",
    spicyLevel: 4,
    fermentationLevel: 4,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["갓", "고춧가루", "젓갈", "마늘"],
    bestWith: ["고기구이", "굴밥", "밥"],
    healthBenefits: ["항암 효과", "비타민 A", "철분"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Gat-kimchi.jpg/800px-Gat-kimchi.jpg",
    tags: ["전라도", "알싸함", "향긋함"],
  },
  {
    id: "pa",
    name: "파김치",
    nameEn: "Green Onion Kimchi",
    description: "쪽파나 실파를 통째로 양념에 버무린 김치로, 고기와 궁합이 좋습니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 2,
    mainIngredients: ["쪽파", "고춧가루", "젓갈", "마늘"],
    bestWith: ["삼겹살", "불고기", "제육볶음"],
    healthBenefits: ["혈액순환", "항균 작용", "비타민 C"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Pa-kimchi.jpg/800px-Pa-kimchi.jpg",
    tags: ["고기안주", "향긋함"],
  },
  {
    id: "bossam",
    name: "보쌈김치",
    nameEn: "Wrapped Kimchi",
    description: "배추잎에 여러 해산물과 과일을 넣어 싸서 담근 궁중식 고급 김치입니다.",
    region: "서울/경기",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["배추", "굴", "낙지", "밤", "대추", "배"],
    bestWith: ["특별한 식사", "명절", "손님상"],
    healthBenefits: ["단백질", "미네랄", "영양 균형"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["고급", "궁중", "해산물", "특별"],
  },
  {
    id: "baek",
    name: "백김치",
    nameEn: "White Kimchi",
    description: "고춧가루를 넣지 않고 담근 하얀 김치. 담백하고 시원한 맛이 특징입니다.",
    region: "전국",
    spicyLevel: 0,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["배추", "무", "배", "밤", "대추"],
    bestWith: ["어린이 식사", "환자식", "담백한 식사"],
    healthBenefits: ["소화 촉진", "위장 보호"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Baek-kimchi.jpg/800px-Baek-kimchi.jpg",
    tags: ["순한맛", "어린이", "담백"],
  },
  {
    id: "buchu",
    name: "부추김치",
    nameEn: "Chive Kimchi",
    description: "부추를 양념에 버무린 김치로, 향긋한 향과 부드러운 식감이 특징입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["부추", "고춧가루", "멸치액젓"],
    bestWith: ["비빔밥", "국수", "고기"],
    healthBenefits: ["스태미나", "비타민 A", "철분"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Buchu-kimchi.jpg/800px-Buchu-kimchi.jpg",
    tags: ["향긋함", "부드러움", "스태미나"],
  },
  // 추가 김치 종류 (13-50)
  {
    id: "mumallaengi",
    name: "무말랭이김치",
    nameEn: "Dried Radish Kimchi",
    description: "무를 말려서 양념에 버무린 김치. 쫄깃한 식감과 고소한 맛이 특징입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["무말랭이", "고춧가루", "간장", "참기름"],
    bestWith: ["도시락", "밥", "술안주"],
    healthBenefits: ["식이섬유", "소화 촉진"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Kkakdugi.jpg/800px-Kkakdugi.jpg",
    tags: ["쫄깃함", "고소함", "밑반찬"],
  },
  {
    id: "godeulppaegi",
    name: "고들빼기김치",
    nameEn: "Korean Lettuce Kimchi",
    description: "고들빼기의 쌉싸름한 맛이 특징인 전라도 향토 김치입니다.",
    region: "전라도",
    spicyLevel: 3,
    fermentationLevel: 4,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["고들빼기", "고춧가루", "젓갈", "마늘"],
    bestWith: ["보리밥", "된장국", "고기"],
    healthBenefits: ["간 건강", "해독 작용", "소화 촉진"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["전라도", "쌉싸름", "향토"],
  },
  {
    id: "kkaennip",
    name: "깻잎김치",
    nameEn: "Perilla Leaf Kimchi",
    description: "깻잎을 양념장에 절여 만든 김치. 향긋한 깻잎 향이 특징입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 3,
    crunchiness: 2,
    mainIngredients: ["깻잎", "간장", "고춧가루", "마늘"],
    bestWith: ["쌈밥", "고기", "비빔밥"],
    healthBenefits: ["철분", "칼슘", "항알러지"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Perilla_Leaf_Kimchi.jpg/800px-Perilla_Leaf_Kimchi.jpg",
    tags: ["향긋함", "쌈", "밑반찬"],
  },
  {
    id: "minari",
    name: "미나리김치",
    nameEn: "Water Parsley Kimchi",
    description: "미나리 특유의 향과 아삭한 식감이 살아있는 봄철 별미 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["미나리", "고춧가루", "멸치액젓", "마늘"],
    bestWith: ["삼겹살", "매운탕", "해장국"],
    healthBenefits: ["해독 작용", "혈액 정화", "비타민"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "향긋함", "해독"],
  },
  {
    id: "seokbakji",
    name: "석박지",
    nameEn: "Mixed Vegetable Kimchi",
    description: "무와 배추를 큼직하게 썰어 담근 시원한 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["무", "배추", "고춧가루", "젓갈"],
    bestWith: ["칼국수", "수제비", "면요리"],
    healthBenefits: ["소화 촉진", "비타민 C"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Nabak-kimchi.jpg/800px-Nabak-kimchi.jpg",
    tags: ["시원함", "면요리", "담백"],
  },
  {
    id: "museongchae",
    name: "무생채",
    nameEn: "Fresh Radish Salad Kimchi",
    description: "무를 채 썰어 고춧가루 양념에 버무린 즉석 김치입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 5,
    mainIngredients: ["무", "고춧가루", "식초", "설탕"],
    bestWith: ["불고기", "갈비", "고기요리"],
    healthBenefits: ["소화 촉진", "비타민 C", "칼륨"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Kkakdugi.jpg/800px-Kkakdugi.jpg",
    tags: ["즉석", "아삭함", "새콤달콤"],
  },
  {
    id: "goguma",
    name: "고구마줄기김치",
    nameEn: "Sweet Potato Stem Kimchi",
    description: "고구마줄기의 질긴 식감과 구수한 맛이 특징인 여름 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["고구마줄기", "된장", "고춧가루", "들깨"],
    bestWith: ["보리밥", "된장찌개", "비빔밥"],
    healthBenefits: ["식이섬유", "철분", "비타민"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["여름", "구수함", "시골"],
  },
  {
    id: "kongnamul",
    name: "콩나물김치",
    nameEn: "Bean Sprout Kimchi",
    description: "아삭한 콩나물에 양념을 버무린 즉석 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 5,
    mainIngredients: ["콩나물", "고춧가루", "파", "마늘"],
    bestWith: ["해장국", "비빔밥", "밥"],
    healthBenefits: ["아스파라긴산", "해독", "숙취해소"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Kongnamul-muchim.jpg/800px-Kongnamul-muchim.jpg",
    tags: ["즉석", "아삭함", "해장"],
  },
  {
    id: "yangbaechu",
    name: "양배추김치",
    nameEn: "Cabbage Kimchi",
    description: "양배추로 담근 김치. 부드럽고 달콤한 맛이 특징입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["양배추", "고춧가루", "멸치액젓", "마늘"],
    bestWith: ["돈까스", "양식", "샌드위치"],
    healthBenefits: ["위장 건강", "비타민 U", "항산화"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["부드러움", "달콤함", "퓨전"],
  },
  {
    id: "putbaechu",
    name: "풋배추김치",
    nameEn: "Young Cabbage Kimchi",
    description: "어린 배추로 담근 봄철 별미 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["풋배추", "고춧가루", "멸치액젓", "마늘"],
    bestWith: ["삼겹살", "된장찌개", "보리밥"],
    healthBenefits: ["비타민 C", "엽산", "칼슘"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "어린배추", "신선함"],
  },
  {
    id: "altari",
    name: "알타리김치",
    nameEn: "Baby Radish Kimchi",
    description: "작은 알타리무로 담근 아삭하고 알싸한 김치입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 5,
    mainIngredients: ["알타리무", "고춧가루", "젓갈", "마늘"],
    bestWith: ["삼겹살", "보쌈", "수육"],
    healthBenefits: ["소화 촉진", "항산화"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Chonggak-kimchi.jpg/800px-Chonggak-kimchi.jpg",
    tags: ["아삭함", "알싸함", "고기"],
  },
  {
    id: "sulkimchi",
    name: "술김치",
    nameEn: "Rice Wine Kimchi",
    description: "막걸리를 넣어 담근 달큰하고 부드러운 김치입니다.",
    region: "충청도",
    spicyLevel: 1,
    fermentationLevel: 4,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["배추", "막걸리", "고춧가루", "마늘"],
    bestWith: ["밥", "국", "한정식"],
    healthBenefits: ["유산균", "소화 촉진"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["충청도", "달큼함", "부드러움"],
  },
  {
    id: "jangkimchi",
    name: "장김치",
    nameEn: "Soy Sauce Kimchi",
    description: "간장 양념으로 담근 담백하고 깔끔한 김치입니다.",
    region: "전국",
    spicyLevel: 0,
    fermentationLevel: 2,
    saltiness: 3,
    crunchiness: 4,
    mainIngredients: ["배추", "간장", "마늘", "생강"],
    bestWith: ["한정식", "밥", "죽"],
    healthBenefits: ["소화 촉진", "위장 보호"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["담백함", "순한맛", "간장"],
  },
  {
    id: "sukchae",
    name: "숙채김치",
    nameEn: "Blanched Vegetable Kimchi",
    description: "데친 채소에 양념을 버무린 부드러운 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["시금치", "콩나물", "고춧가루", "참기름"],
    bestWith: ["비빔밥", "밥", "한정식"],
    healthBenefits: ["철분", "비타민", "식이섬유"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["부드러움", "즉석", "나물"],
  },
  {
    id: "ueong",
    name: "우엉김치",
    nameEn: "Burdock Root Kimchi",
    description: "우엉의 향긋하고 쫄깃한 식감이 특징인 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["우엉", "간장", "고춧가루", "참기름"],
    bestWith: ["도시락", "밥", "김밥"],
    healthBenefits: ["식이섬유", "혈당 조절", "해독"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["쫄깃함", "향긋함", "밑반찬"],
  },
  {
    id: "doraji",
    name: "도라지김치",
    nameEn: "Bellflower Root Kimchi",
    description: "도라지의 쌉싸름하고 아삭한 맛이 특징인 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["도라지", "고춧가루", "간장", "참기름"],
    bestWith: ["한정식", "밥", "나물"],
    healthBenefits: ["기관지 건강", "면역력", "사포닌"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["쌉싸름", "기관지", "건강"],
  },
  {
    id: "myeolchi",
    name: "멸치젓무침",
    nameEn: "Anchovy Kimchi",
    description: "멸치젓에 무채를 버무린 짭짤한 밑반찬입니다.",
    region: "남해안",
    spicyLevel: 3,
    fermentationLevel: 4,
    saltiness: 5,
    crunchiness: 3,
    mainIngredients: ["멸치젓", "무", "고춧가루", "마늘"],
    bestWith: ["밥", "비빔밥", "술안주"],
    healthBenefits: ["칼슘", "단백질", "오메가3"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["짭짤함", "젓갈", "남해안"],
  },
  {
    id: "gochu",
    name: "고추김치",
    nameEn: "Pepper Kimchi",
    description: "풋고추나 청양고추를 통째로 담근 매콤한 김치입니다.",
    region: "전국",
    spicyLevel: 5,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 4,
    mainIngredients: ["고추", "젓갈", "마늘", "생강"],
    bestWith: ["삼겹살", "소주", "밥"],
    healthBenefits: ["비타민 C", "캡사이신", "신진대사"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["매운맛", "고추", "술안주"],
  },
  {
    id: "maneul",
    name: "마늘김치",
    nameEn: "Garlic Kimchi",
    description: "통마늘을 절여 담근 김치. 알싸하고 감칠맛이 좋습니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 4,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["마늘", "간장", "고춧가루"],
    bestWith: ["고기", "밥", "술안주"],
    healthBenefits: ["항균", "면역력", "피로회복"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["마늘", "감칠맛", "건강"],
  },
  {
    id: "changnan",
    name: "창난젓김치",
    nameEn: "Pollack Roe Kimchi",
    description: "명태 창난젓에 무채를 버무린 짭짤한 김치입니다.",
    region: "강원도",
    spicyLevel: 3,
    fermentationLevel: 4,
    saltiness: 5,
    crunchiness: 3,
    mainIngredients: ["창난젓", "무", "고춧가루", "참기름"],
    bestWith: ["밥", "술안주", "비빔밥"],
    healthBenefits: ["단백질", "오메가3"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["강원도", "젓갈", "짭짤함"],
  },
  {
    id: "sigeumchi",
    name: "시금치김치",
    nameEn: "Spinach Kimchi",
    description: "시금치를 데쳐서 양념에 버무린 부드러운 김치입니다.",
    region: "전국",
    spicyLevel: 1,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["시금치", "고춧가루", "참기름", "깨"],
    bestWith: ["비빔밥", "밥", "한정식"],
    healthBenefits: ["철분", "엽산", "비타민 K"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["부드러움", "나물", "영양"],
  },
  {
    id: "sukjunamul",
    name: "숙주나물김치",
    nameEn: "Mung Bean Sprout Kimchi",
    description: "아삭한 숙주나물에 양념을 버무린 즉석 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 5,
    mainIngredients: ["숙주나물", "고춧가루", "파", "마늘"],
    bestWith: ["쌀국수", "비빔밥", "불고기"],
    healthBenefits: ["비타민 C", "해독", "저칼로리"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["즉석", "아삭함", "가벼움"],
  },
  {
    id: "gulkimchi",
    name: "굴김치",
    nameEn: "Oyster Kimchi",
    description: "신선한 굴을 넣어 담근 겨울철 별미 김치입니다.",
    region: "서해안",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["배추", "굴", "고춧가루", "젓갈"],
    bestWith: ["밥", "굴밥", "한정식"],
    healthBenefits: ["아연", "철분", "타우린"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["겨울", "굴", "바다"],
  },
  {
    id: "jokbal",
    name: "족발김치",
    nameEn: "Pigs Feet Kimchi Wrap",
    description: "족발과 함께 먹는 겉절이 스타일의 신선한 김치입니다.",
    region: "전국",
    spicyLevel: 3,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["배추", "무", "고춧가루", "새우젓"],
    bestWith: ["족발", "보쌈", "막국수"],
    healthBenefits: ["비타민 C", "소화 촉진"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["겉절이", "족발", "신선함"],
  },
  {
    id: "jeotgal",
    name: "젓국지",
    nameEn: "Fermented Fish Kimchi",
    description: "새우젓국물로 담근 시원하고 깊은 맛의 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 4,
    saltiness: 4,
    crunchiness: 3,
    mainIngredients: ["배추", "새우젓국", "마늘", "생강"],
    bestWith: ["밥", "국", "찌개"],
    healthBenefits: ["유산균", "단백질"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["젓갈", "깊은맛", "전통"],
  },
  {
    id: "hobak",
    name: "호박김치",
    nameEn: "Zucchini Kimchi",
    description: "애호박을 이용해 담근 여름철 별미 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["애호박", "새우젓", "고춧가루", "마늘"],
    bestWith: ["밥", "된장찌개", "여름밥상"],
    healthBenefits: ["비타민 A", "저칼로리", "수분"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["여름", "호박", "가벼움"],
  },
  {
    id: "gaji",
    name: "가지김치",
    nameEn: "Eggplant Kimchi",
    description: "가지를 쪄서 양념장에 버무린 부드러운 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["가지", "간장", "고춧가루", "참기름"],
    bestWith: ["밥", "비빔밥", "고기"],
    healthBenefits: ["안토시아닌", "항산화", "식이섬유"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["여름", "부드러움", "가지"],
  },
  {
    id: "dalrae",
    name: "달래김치",
    nameEn: "Wild Chive Kimchi",
    description: "봄 달래의 알싸하고 향긋한 맛이 특징인 봄철 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["달래", "고춧가루", "멸치액젓", "참기름"],
    bestWith: ["삼겹살", "된장찌개", "봄나물"],
    healthBenefits: ["비타민 C", "철분", "봄철 피로회복"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "향긋함", "달래"],
  },
  {
    id: "naengi",
    name: "냉이김치",
    nameEn: "Shepherds Purse Kimchi",
    description: "봄 냉이의 구수하고 향긋한 맛이 살아있는 계절 김치입니다.",
    region: "전국",
    spicyLevel: 1,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["냉이", "된장", "고춧가루", "마늘"],
    bestWith: ["보리밥", "된장국", "봄나물밥"],
    healthBenefits: ["비타민 A", "칼슘", "간 건강"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "구수함", "냉이"],
  },
  {
    id: "ssuk",
    name: "쑥김치",
    nameEn: "Mugwort Kimchi",
    description: "쑥의 쌉싸름하고 향긋한 맛이 특징인 봄철 건강 김치입니다.",
    region: "전국",
    spicyLevel: 1,
    fermentationLevel: 2,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["쑥", "고춧가루", "된장", "마늘"],
    bestWith: ["밥", "삼계탕", "보양식"],
    healthBenefits: ["철분", "항산화", "여성 건강"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "건강", "쑥"],
  },
  {
    id: "buchukimchi",
    name: "부추겉절이",
    nameEn: "Fresh Chive Kimchi",
    description: "부추를 바로 버무려 먹는 신선한 겉절이 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["부추", "고춧가루", "멸치액젓", "참기름"],
    bestWith: ["삼겹살", "오리고기", "불고기"],
    healthBenefits: ["스태미나", "비타민 A", "혈액순환"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["겉절이", "고기", "신선함"],
  },
  {
    id: "sangchu",
    name: "상추김치",
    nameEn: "Lettuce Kimchi",
    description: "상추를 겉절이로 담근 시원하고 가벼운 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 1,
    saltiness: 2,
    crunchiness: 2,
    mainIngredients: ["상추", "고춧가루", "멸치액젓", "참기름"],
    bestWith: ["삼겹살", "불고기", "쌈밥"],
    healthBenefits: ["식이섬유", "비타민", "저칼로리"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["겉절이", "가벼움", "쌈"],
  },
  {
    id: "yulmukimchi",
    name: "율무김치",
    nameEn: "Jobs Tears Kimchi",
    description: "율무를 넣어 담근 건강 김치. 고소하고 담백한 맛입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 3,
    mainIngredients: ["배추", "율무", "고춧가루", "마늘"],
    bestWith: ["밥", "죽", "건강식"],
    healthBenefits: ["피부 건강", "부종 완화", "다이어트"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["건강", "율무", "다이어트"],
  },
  {
    id: "jukkumi",
    name: "쭈꾸미김치",
    nameEn: "Webfoot Octopus Kimchi",
    description: "쭈꾸미를 넣어 담근 특별한 봄철 별미 김치입니다.",
    region: "서해안",
    spicyLevel: 4,
    fermentationLevel: 2,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["배추", "쭈꾸미", "고춧가루", "젓갈"],
    bestWith: ["밥", "술안주", "봄 별미"],
    healthBenefits: ["타우린", "단백질", "철분"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["봄", "해산물", "별미"],
  },
  {
    id: "jogaejeotgal",
    name: "조개젓김치",
    nameEn: "Clam Kimchi",
    description: "조개젓으로 담근 시원하고 감칠맛 나는 김치입니다.",
    region: "서해안",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 4,
    crunchiness: 3,
    mainIngredients: ["배추", "조개젓", "고춧가루", "마늘"],
    bestWith: ["밥", "해물탕", "칼국수"],
    healthBenefits: ["철분", "아연", "타우린"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["서해안", "조개", "감칠맛"],
  },
  {
    id: "kodari",
    name: "코다리김치",
    nameEn: "Semi-dried Pollack Kimchi",
    description: "코다리를 넣어 담근 강원도 향토 김치입니다.",
    region: "강원도",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 4,
    crunchiness: 3,
    mainIngredients: ["배추", "코다리", "고춧가루", "젓갈"],
    bestWith: ["밥", "된장찌개", "막국수"],
    healthBenefits: ["단백질", "오메가3", "칼슘"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["강원도", "코다리", "향토"],
  },
  {
    id: "meokgalkimchi",
    name: "먹갈김치",
    nameEn: "Aged Perilla Leaf Kimchi",
    description: "깻잎을 오래 삭혀 담근 깊은 맛의 김치입니다.",
    region: "전라도",
    spicyLevel: 2,
    fermentationLevel: 5,
    saltiness: 4,
    crunchiness: 1,
    mainIngredients: ["깻잎", "간장", "고춧가루", "마늘"],
    bestWith: ["밥", "보쌈", "한정식"],
    healthBenefits: ["철분", "향균", "소화촉진"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["전라도", "삭힌", "깊은맛"],
  },
  {
    id: "ggwarigochu",
    name: "꽈리고추김치",
    nameEn: "Shishito Pepper Kimchi",
    description: "꽈리고추를 간장 양념에 조린 밑반찬 김치입니다.",
    region: "전국",
    spicyLevel: 2,
    fermentationLevel: 2,
    saltiness: 3,
    crunchiness: 2,
    mainIngredients: ["꽈리고추", "간장", "마늘", "참기름"],
    bestWith: ["밥", "도시락", "비빔밥"],
    healthBenefits: ["비타민 C", "캡사이신"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["밑반찬", "간장", "도시락"],
  },
  {
    id: "ojingeo",
    name: "오징어젓김치",
    nameEn: "Squid Kimchi",
    description: "오징어젓을 넣어 담근 쫄깃하고 감칠맛 나는 김치입니다.",
    region: "동해안",
    spicyLevel: 3,
    fermentationLevel: 4,
    saltiness: 4,
    crunchiness: 3,
    mainIngredients: ["배추", "오징어젓", "고춧가루", "마늘"],
    bestWith: ["밥", "술안주", "비빔밥"],
    healthBenefits: ["타우린", "단백질"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["동해안", "오징어", "감칠맛"],
  },
  {
    id: "jinju",
    name: "진주김치",
    nameEn: "Jinju Style Kimchi",
    description: "경상남도 진주 지역의 전통 김치. 담백하고 깔끔합니다.",
    region: "경상남도",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 2,
    crunchiness: 4,
    mainIngredients: ["배추", "미나리", "젓갈", "마늘"],
    bestWith: ["비빔밥", "한정식", "밥"],
    healthBenefits: ["비타민", "미네랄"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["경상남도", "진주", "담백"],
  },
  {
    id: "andong",
    name: "안동김치",
    nameEn: "Andong Style Kimchi",
    description: "경상북도 안동의 전통 김치. 간장을 사용해 담백합니다.",
    region: "경상북도",
    spicyLevel: 1,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 4,
    mainIngredients: ["배추", "간장", "마늘", "생강"],
    bestWith: ["안동찜닭", "간고등어", "한정식"],
    healthBenefits: ["발효식품", "유산균"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["경상북도", "안동", "간장"],
  },
  {
    id: "geoje",
    name: "거제도김치",
    nameEn: "Geoje Island Kimchi",
    description: "거제도의 신선한 해산물을 넣은 바다 향 가득한 김치입니다.",
    region: "경상남도",
    spicyLevel: 3,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 4,
    mainIngredients: ["배추", "멸치", "굴", "새우"],
    bestWith: ["회", "해물찜", "밥"],
    healthBenefits: ["오메가3", "미네랄", "타우린"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["섬김치", "해산물", "거제도"],
  },
  {
    id: "jeju",
    name: "제주김치",
    nameEn: "Jeju Island Kimchi",
    description: "제주도의 전복과 해산물을 넣은 특별한 섬김치입니다.",
    region: "제주도",
    spicyLevel: 2,
    fermentationLevel: 3,
    saltiness: 3,
    crunchiness: 3,
    mainIngredients: ["배추", "전복", "톳", "멸치"],
    bestWith: ["흑돼지", "해물뚝배기", "제주음식"],
    healthBenefits: ["타우린", "미네랄", "항산화"],
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Kimchi-chinese_cabbage.jpg/800px-Kimchi-chinese_cabbage.jpg",
    tags: ["제주도", "전복", "섬김치"],
  },
];

// 퀴즈 질문 정의
export interface QuizQuestion {
  id: string;
  question: string;
  options: {
    id: string;
    label: string;
    scores: {
      spicy?: number;
      fermented?: number;
      crunchy?: number;
      mild?: number;
      refreshing?: number;
    };
  }[];
}

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: "spicy",
    question: "매운 음식을 얼마나 좋아하시나요?",
    options: [
      { id: "none", label: "매운 건 못 먹어요", scores: { spicy: 0, mild: 5 } },
      { id: "mild", label: "약간 매운 정도가 좋아요", scores: { spicy: 2, mild: 3 } },
      { id: "medium", label: "적당히 매운 게 좋아요", scores: { spicy: 3 } },
      { id: "hot", label: "매울수록 좋아요!", scores: { spicy: 5 } },
    ],
  },
  {
    id: "texture",
    question: "어떤 식감을 선호하시나요?",
    options: [
      { id: "crunchy", label: "아삭아삭한 식감", scores: { crunchy: 5 } },
      { id: "soft", label: "부드러운 식감", scores: { crunchy: 1, fermented: 3 } },
      { id: "mixed", label: "둘 다 좋아요", scores: { crunchy: 3, fermented: 2 } },
    ],
  },
  {
    id: "fermentation",
    question: "발효된 신맛을 좋아하시나요?",
    options: [
      { id: "fresh", label: "겉절이처럼 신선한 게 좋아요", scores: { fermented: 1 } },
      { id: "medium", label: "적당히 익은 게 좋아요", scores: { fermented: 3 } },
      { id: "well", label: "잘 익은 신맛이 좋아요", scores: { fermented: 5 } },
    ],
  },
  {
    id: "purpose",
    question: "김치를 주로 어떻게 드시나요?",
    options: [
      { id: "rice", label: "밥이랑 먹어요", scores: { fermented: 3, spicy: 3 } },
      { id: "meat", label: "고기랑 먹어요", scores: { crunchy: 4, spicy: 3 } },
      { id: "soup", label: "국물 요리와 먹어요", scores: { crunchy: 5, refreshing: 3 } },
      { id: "noodle", label: "면 요리와 먹어요", scores: { refreshing: 5, crunchy: 3 } },
    ],
  },
  {
    id: "season",
    question: "지금 계절에 어울리는 김치를 원하시나요?",
    options: [
      { id: "spring", label: "봄 - 산뜻한 김치", scores: { refreshing: 4, crunchy: 3 } },
      { id: "summer", label: "여름 - 시원한 김치", scores: { refreshing: 5, spicy: 1 } },
      { id: "fall", label: "가을 - 깊은 맛 김치", scores: { fermented: 4, spicy: 3 } },
      { id: "winter", label: "겨울 - 든든한 김치", scores: { fermented: 5, spicy: 4 } },
    ],
  },
];

// 점수에 따른 김치 추천 로직
export function recommendKimchi(
  scores: { spicy: number; fermented: number; crunchy: number; mild: number; refreshing: number }
): KimchiType[] {
  const kimchiScores = KIMCHI_DATA.map((kimchi) => {
    let score = 0;

    // 매운맛 점수
    if (scores.mild > 3) {
      score += kimchi.spicyLevel === 0 || kimchi.spicyLevel === 1 ? 20 : -10;
    } else {
      score += Math.abs(kimchi.spicyLevel - (scores.spicy || 3)) <= 1 ? 15 : 0;
    }

    // 발효 점수
    const fermentedDiff = Math.abs(kimchi.fermentationLevel - (scores.fermented || 3));
    score += (5 - fermentedDiff) * 4;

    // 아삭함 점수
    const crunchyDiff = Math.abs(kimchi.crunchiness - (scores.crunchy || 3));
    score += (5 - crunchyDiff) * 3;

    // 시원함 점수 (물김치 보너스)
    if (scores.refreshing > 3) {
      if (kimchi.tags.includes("물김치") || kimchi.tags.includes("시원함")) {
        score += 15;
      }
    }

    return { kimchi, score };
  });

  // 점수 순으로 정렬하여 상위 3개 반환
  return kimchiScores
    .sort((a, b) => b.score - a.score)
    .slice(0, 3)
    .map((item) => item.kimchi);
}
